gem 'geocoder'

gem 'dotenv'
gem 'browser'

gem 'will-paginate-i18n'
gem 'utf8-cleaner'
gem 'premailer-rails'
gem 'message_bus'

gem 'rack-timeout'

# js
# while https://github.com/rails-api/active_model_serializers/issues/1143 is not released
gem 'active_model_serializers', '0.10.0'
gem 'i18n-js'
gem 'js-routes', '= 1.2.6'
gem 'riot_js-rails'#, path: '../../others/riot_js-rails'
gem 'sprockets-es6'

group :assets do
  gem 'assets_live_compile', '>= 0.2.1'
  gem 'therubyracer' # for fast js template compilations
end

group :development do
  gem 'pry'
  #gem 'byebug', platform: :mri

  gem 'better_errors'
  gem 'binding_of_caller'

  gem 'wirble'

  gem 'html2haml', require: false
  gem 'haml2slim', require: false
end

gem 'redis-rails'

gem 'mailgun_rails'

gem 'newrelic_rpm'
gem 'rollbar'

platform :ruby do
  gem 'unicode'
  group :performance do

    # FIXME: stack level too deep
    gem 'oj', '~> 2.0'
    gem 'oj_mimic_json'

    gem 'fast_blank'
    gem 'gctools' if RUBY_VERSION >= '2.1.0' and RUBY_VERSION < '2.2.0'
    # DON'T IMPROVE
    #gem 'escape_utils'

    #gem 'rack-cache'
    #gem 'redis-rack-cache'
    
    gem 'stackprof', platform: :mri
    gem 'flamegraph', platform: :mri
  end

  group :production do
    gem 'unicorn-worker-killer'
    gem 'puma_worker_killer'
  end
end

