gem 'geocoder'

gem 'dotenv'

group :development do
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :production do
  gem 'mailgun_rails'
  gem 'rollbar'
  gem 'puma_worker_killer'
end

